### ISSUE TITLE
Involuntary talent reset

### ISSUE THREAD

**Issue by Malorh** [fusionpit/TalentSequence#1]
When removing a point so you have too few points in the tree to allow already chosen deeper level talents, the deeper talents are removed. This is rather annoying, as you now have to click everything once more.

In my opinion: The point should simply not be removed no matter how many times the user right clicks the talent. This is how all other talent calculators work and it feels intuitive.

Edit: Okay I just found the reddit thread linking to here and I can see someone reported this issue a few days ago. Well, now you have it as an issue on github so it is easier to remember ;)

**Comment by fusionpit** [comment]
Hi @Malorh,
Is your issue related to the bobo-talents website?

**Comment by Malorh** [comment]
Sorry, I didn't notice the response before now.

Yes. https://bobo-talents.aerobaticapp.com/

**Comment by fusionpit** [comment]
Thanks for the reply.  I do not have an affiliation with bobo-talents, I just made the addon to take advantage of the sequencing feature.  I will be sure to forward this issue to the site owner, so thanks for the report!
