### ISSUE TITLE
1.12 version loading

### ISSUE THREAD

**Issue by Road-block** [fusionpit/TalentSequence#2]
Only way I had addon load on 1.12 is with this change to the .toc
```
## Dependencies: Blizzard_TalentUI
```
Which is to force the addon to only load after Blizzard_TalentUI loads.
and 
```lua
local talentSequenceEventFrame = CreateFrame("Frame");
talentSequenceEventFrame:SetScript("OnEvent", function()
    if (not TalentSequenceTalents) then
        TalentSequenceTalents = {};
    end
    if (IsTalentSequenceExpanded == 0) then
        IsTalentSequenceExpanded = false;
    end
end);
talentSequenceEventFrame:RegisterEvent("VARIABLES_LOADED");
TalentSequence_CreateFrame();
```
at the tail end of TalentSequence.lua

**Comment by fusionpit** [comment]
That is interesting, since the TalentUI is Load On Demand and Talent Sequence is not.  It should just work, like it does for me...

@Road-block, can you run the command `/run local a,b,c=GetBuildInfo();DEFAULT_CHAT_FRAME:AddMessage(format("version=%s, build=%s, date=%s",a,b,c))` in game and tell me the output?  I want to make sure it's not a client issue.

**Comment by Road-block** [comment]
`version=1.12.1, build=5875, date=Sep 19 2006`

**Comment by fusionpit** [comment]
Yep, same as mine.  What other addons are you using?

**Comment by Road-block** [comment]
Client loading process changed through expansions.  
In 1.12 the event signifying addon saved variables load is `VARIABLES_LOADED`

In later expansions (and modern wow) `VARIABLES_LOADED` was re-purposed to signify loading of Blizzard saved variables and decoupled from user addons, whose saved variables loading (LoD aside) is now linked to `ADDON_LOADED` where arg1 == 'addonName`.  

Depending on addons the user is running (in 1.12) it can happen that by the time your specific `ADDON_LOADED` event fires `VARIABLES_LOADED` has also fired and so initialization can work *coincidentally* but will not work for all users.

To answer your question though, I am running a bunch of other addons but no addons that replace or modify Blizzard_TalentUI.  

`# RequiredDeps` (or the synonymous `# Dependencies`) causes the client to defer loading of Addon A (TalentSequence) until Addon B (Blizzard_TalentUI) regardless of LoadOnDemand status.  
To dynamically load TalentSequence when Blizzard_TalentUI loads explicitlyb a pair of .toc tags would instead be needed:  
- `# LoadOnDemand: 1`
- `# LoadWith: Blizzard_TalentUI`

**Comment by fusionpit** [comment]
Thanks for the great info!  It's not too easy to find stuff like this searching the general web.  I'll be sure to get some changes made to make it work more generally.

**Comment by fusionpit** [comment]
Can you try the beta version available at https://github.com/fusionpit/TalentSequence/releases/tag/1.1v-beta1 and see if it fixes your issue?

**Comment by Road-block** [comment]
![image](https://user-images.githubusercontent.com/109839/60382626-72866080-9a6e-11e9-9747-c294a93d9328.png)
Tested both cold login as well as /console reloadui (loading sequence is slightly different in each case)  
Works fine now, good job 😃 

@dein0s

**Comment by fusionpit** [comment]
Thank you for the confirmation, I appreciate it.
