### ISSUE TITLE
Cross-contamination of settings

### ISSUE THREAD

**Issue by colgraff** [fusionpit/TalentSequence#7]
In an effort to get the same settings across characters I copied the Saved Variables file from one character to another. Sometimes this works for addons and sometimes it has bad side effects. With Talent Sequence it sets the talent sequence on the new character to a new set but one which might not be desired since it seems to be based on the relative positions for the other class.

Perhaps some detection should be used which will clear the talent sequence if it doesn't apply to the current class. For example, save the class along with the selected talents and if the class doesn't match the current one then clear the talent sequence or provide a warning.

**Comment by fusionpit** [comment]
Thanks for the report.  I'll consider the options available for preventing this.

**Comment by ZekeRyukai** [comment]
This should be a non-issue now. Talents are importable on any class and shared across characters as a baseline implementation. The only SavedVariable aspect that is character specific is each character's currently loaded talent sequence, of which, there should be no need to copy that to another character.
